name: Deploy static content to Lolipop

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 'v18.17.1'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: build static resources
        run: npm run generate
      - name: Deploy via FTPs
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.SSH_ACCOUNT }}
          password: ${{ secrets.SSH_KEY }}
          local-dir: ./.output/public/
          server-dir: ${{ secrets.SERVER_PATH }}/
          protocol: ftps
